/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RadioCountryRouteImport } from './routes/radio/$country'
import { Route as IptvCountryRouteImport } from './routes/iptv/$country'
import { Route as ChannelsSlugRouteImport } from './routes/channels/$slug'
import { Route as RadioCountryStationRouteImport } from './routes/radio/$country/$station'
import { Route as IptvCountryStreamRouteImport } from './routes/iptv/$country/$stream'

const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioCountryRoute = RadioCountryRouteImport.update({
  id: '/radio/$country',
  path: '/radio/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvCountryRoute = IptvCountryRouteImport.update({
  id: '/iptv/$country',
  path: '/iptv/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsSlugRoute = ChannelsSlugRouteImport.update({
  id: '/channels/$slug',
  path: '/channels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioCountryStationRoute = RadioCountryStationRouteImport.update({
  id: '/$station',
  path: '/$station',
  getParentRoute: () => RadioCountryRoute,
} as any)
const IptvCountryStreamRoute = IptvCountryStreamRouteImport.update({
  id: '/$stream',
  path: '/$stream',
  getParentRoute: () => IptvCountryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/channels/$slug': typeof ChannelsSlugRoute
  '/iptv/$country': typeof IptvCountryRouteWithChildren
  '/radio/$country': typeof RadioCountryRouteWithChildren
  '/iptv/$country/$stream': typeof IptvCountryStreamRoute
  '/radio/$country/$station': typeof RadioCountryStationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/channels/$slug': typeof ChannelsSlugRoute
  '/iptv/$country': typeof IptvCountryRouteWithChildren
  '/radio/$country': typeof RadioCountryRouteWithChildren
  '/iptv/$country/$stream': typeof IptvCountryStreamRoute
  '/radio/$country/$station': typeof RadioCountryStationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/channels/$slug': typeof ChannelsSlugRoute
  '/iptv/$country': typeof IptvCountryRouteWithChildren
  '/radio/$country': typeof RadioCountryRouteWithChildren
  '/iptv/$country/$stream': typeof IptvCountryStreamRoute
  '/radio/$country/$station': typeof RadioCountryStationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/channels/$slug'
    | '/iptv/$country'
    | '/radio/$country'
    | '/iptv/$country/$stream'
    | '/radio/$country/$station'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/channels/$slug'
    | '/iptv/$country'
    | '/radio/$country'
    | '/iptv/$country/$stream'
    | '/radio/$country/$station'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/channels/$slug'
    | '/iptv/$country'
    | '/radio/$country'
    | '/iptv/$country/$stream'
    | '/radio/$country/$station'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  ChannelsSlugRoute: typeof ChannelsSlugRoute
  IptvCountryRoute: typeof IptvCountryRouteWithChildren
  RadioCountryRoute: typeof RadioCountryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio/$country': {
      id: '/radio/$country'
      path: '/radio/$country'
      fullPath: '/radio/$country'
      preLoaderRoute: typeof RadioCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv/$country': {
      id: '/iptv/$country'
      path: '/iptv/$country'
      fullPath: '/iptv/$country'
      preLoaderRoute: typeof IptvCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/$slug': {
      id: '/channels/$slug'
      path: '/channels/$slug'
      fullPath: '/channels/$slug'
      preLoaderRoute: typeof ChannelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio/$country/$station': {
      id: '/radio/$country/$station'
      path: '/$station'
      fullPath: '/radio/$country/$station'
      preLoaderRoute: typeof RadioCountryStationRouteImport
      parentRoute: typeof RadioCountryRoute
    }
    '/iptv/$country/$stream': {
      id: '/iptv/$country/$stream'
      path: '/$stream'
      fullPath: '/iptv/$country/$stream'
      preLoaderRoute: typeof IptvCountryStreamRouteImport
      parentRoute: typeof IptvCountryRoute
    }
  }
}

interface IptvCountryRouteChildren {
  IptvCountryStreamRoute: typeof IptvCountryStreamRoute
}

const IptvCountryRouteChildren: IptvCountryRouteChildren = {
  IptvCountryStreamRoute: IptvCountryStreamRoute,
}

const IptvCountryRouteWithChildren = IptvCountryRoute._addFileChildren(
  IptvCountryRouteChildren,
)

interface RadioCountryRouteChildren {
  RadioCountryStationRoute: typeof RadioCountryStationRoute
}

const RadioCountryRouteChildren: RadioCountryRouteChildren = {
  RadioCountryStationRoute: RadioCountryStationRoute,
}

const RadioCountryRouteWithChildren = RadioCountryRoute._addFileChildren(
  RadioCountryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  ChannelsSlugRoute: ChannelsSlugRoute,
  IptvCountryRoute: IptvCountryRouteWithChildren,
  RadioCountryRoute: RadioCountryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
