/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IptvCountryRouteImport } from './routes/iptv/$country'
import { Route as IptvCountryStreamRouteImport } from './routes/iptv/$country/$stream'
import { Route as RadioCountryRouteImport } from './routes/radio/$country'
import { Route as RadioCountryStationRouteImport } from './routes/radio/$country/$station'
import { Route as ChannelsSlugRouteImport } from './routes/channels/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioCountryRoute = RadioCountryRouteImport.update({
  id: '/radio/$country',
  path: '/radio/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvCountryRoute = IptvCountryRouteImport.update({
  id: '/iptv/$country',
  path: '/iptv/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const IptvCountryStreamRoute = IptvCountryStreamRouteImport.update({
  id: '/iptv/$country/$stream',
  path: '/$stream',
  getParentRoute: () => IptvCountryRoute,
} as any)
const ChannelsSlugRoute = ChannelsSlugRouteImport.update({
  id: '/channels/$slug',
  path: '/channels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioCountryStationRoute = RadioCountryStationRouteImport.update({
  id: '/radio/$country/$station',
  path: '/$station',
  getParentRoute: () => RadioCountryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels/$slug': typeof ChannelsSlugRoute
  '/iptv/$country/$stream': typeof IptvCountryStreamRoute
  '/iptv/$country': typeof IptvCountryRoute
  '/radio/$country/$station': typeof RadioCountryStationRoute
  '/radio/$country': typeof RadioCountryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels/$slug': typeof ChannelsSlugRoute
  '/iptv/$country/$stream': typeof IptvCountryStreamRoute
  '/iptv/$country': typeof IptvCountryRoute
  '/radio/$country/$station': typeof RadioCountryStationRoute
  '/radio/$country': typeof RadioCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels/$slug': typeof ChannelsSlugRoute
  '/iptv/$country/$stream': typeof IptvCountryStreamRoute
  '/iptv/$country': typeof IptvCountryRoute
  '/radio/$country/$station': typeof RadioCountryStationRoute
  '/radio/$country': typeof RadioCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels/$slug'
    | '/iptv/$country'
    | '/iptv/$country/$stream'
    | '/radio/$country'
    | '/radio/$country/$station'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels/$slug'
    | '/iptv/$country'
    | '/iptv/$country/$stream'
    | '/radio/$country'
    | '/radio/$country/$station'
  id:
    | '__root__'
    | '/'
    | '/channels/$slug'
    | '/iptv/$country'
    | '/iptv/$country/$stream'
    | '/radio/$country'
    | '/radio/$country/$station'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsSlugRoute: typeof ChannelsSlugRoute
  IptvCountryRoute: typeof IptvCountryRouteWithChildren
  RadioCountryRoute: typeof RadioCountryRouteWithChildren
}

export interface IptvCountryRouteChildren {
  IptvCountryStreamRoute: typeof IptvCountryStreamRoute
}

export interface RadioCountryRouteChildren {
  RadioCountryStationRoute: typeof RadioCountryStationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio/$country': {
      id: '/radio/$country'
      path: '/radio/$country'
      fullPath: '/radio/$country'
      preLoaderRoute: typeof RadioCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv/$country': {
      id: '/iptv/$country'
      path: '/iptv/$country'
      fullPath: '/iptv/$country'
      preLoaderRoute: typeof IptvCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptv/$country/$stream': {
      id: '/iptv/$country/$stream'
      path: '/$stream'
      fullPath: '/iptv/$country/$stream'
      preLoaderRoute: typeof IptvCountryStreamRouteImport
      parentRoute: typeof IptvCountryRouteImport
    }
    '/channels/$slug': {
      id: '/channels/$slug'
      path: '/channels/$slug'
      fullPath: '/channels/$slug'
      preLoaderRoute: typeof ChannelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio/$country/$station': {
      id: '/radio/$country/$station'
      path: '/$station'
      fullPath: '/radio/$country/$station'
      preLoaderRoute: typeof RadioCountryStationRouteImport
      parentRoute: typeof RadioCountryRouteImport
    }
  }
}

const iptvCountryRouteChildren: IptvCountryRouteChildren = {
  IptvCountryStreamRoute: IptvCountryStreamRoute,
}

const iptvCountryRouteWithChildren = IptvCountryRoute._addFileChildren(
  iptvCountryRouteChildren,
)

const radioCountryRouteChildren: RadioCountryRouteChildren = {
  RadioCountryStationRoute: RadioCountryStationRoute,
}

const radioCountryRouteWithChildren = RadioCountryRoute._addFileChildren(
  radioCountryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsSlugRoute: ChannelsSlugRoute,
  IptvCountryRoute: iptvCountryRouteWithChildren,
  RadioCountryRoute: radioCountryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
